main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Readings
    url: /readings/
    weight: 3
  - name: Data Camp
    url: /datacamp/
    weight: 4
  - name: Materials
    url: /materials/
    weight: 5
  - name: Tasks
    url: /tasks/
    weight: 6
  - name: To Do List
    url: /due/
    weight: 7
  - name: Resources
    url: /resources/
    weight: 8
  - name: Professor
    url: /professor/
    weight: 9
  - name: '<i class="fab fa-slack"></i>'
    url: "https://2021edp693g.slack.com"
    weight: 10
  - name: '<i class="fab fa-r-project"></i>'
    url: "https://rstudio.cloud/"
    weight: 11

readings:
  - name: Overview
    weight: 1
  - name: Print
    weight: 2
datacamp:
  - name: Overview
    weight: 1
  - name: Modules
    weight: 2
materials:
  - name: Overview
    weight: 1
  - name: Content
    weight: 2
  - name: Walkthroughs
    weight: 3
tasks:
  - name: Overview
    weight: 1
  - name: Homeworks
    weight: 2
  - name: Final Proposal
    weight: 3
  - name: Final Project
    weight: 4
due:
  - name: Overview
    weight: 1
  - name: To Do
    weight: 2
resources:
  - name: Overview
    weight: 1
  - name: Guides
    weight: 2
  - name: References
    weight: 3
