main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Readings
    url: /readings/
    weight: 2
  - name: Tasks & Deliverables
    url: /tasks/
    weight: 3
  - name: Due
    url: /due/
    weight: 4
  - name: Resources
    url: /resources/
    weight: 5
  - name: Professor
    url: /professor/
    weight: 6
  - name: '<i class="fab fa-slack"></i>'
    url: "https://edp617spring2023.slack.com"
    weight: 7
  - name: 'Made with <i class="fab fa-r-project"></i>'
    url: "https://www.r-project.org"
    weight: 8
  - name: 'in <b>RStudio</b>'
    url: "https://posit.co/products/open-source/rstudio/"
    weight: 9

readings:
  - name: Overview
    weight: 1
  - name: Readings
    weight: 2
tasks:
  - name: Overview
    weight: 1
  - name: Tasks
    weight: 2
  - name: Deliverables
    weight: 3
due:
  - name: Overview
    weight: 1
  - name: To Do List
    weight: 2
resources:
  - name: Overview
    weight: 1
  - name: Guides
    weight: 2
  - name: References
    weight: 3
