main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Readings
    url: /readings/
    weight: 2
  - name: Materials
    url: /materials/
    weight: 3
  - name: Tasks & Deliverables
    url: /tasks/
    weight: 4
  - name: Due
    url: /due/
    weight: 5
  - name: Resources
    url: /resources/
    weight: 6
  - name: Professor
    url: /professor/
    weight: 7
  - name: '<i class="fab fa-slack"></i>'
    url: "https://edp618fall2022.slack.com"
    weight: 8
  - name: '<i class="fab fa-r-project"></i>'
    url: "https://www.rstudio.com/"
    weight: 9

readings:
  - name: Overview
    weight: 1
  - name: Readings
    weight: 2
Materials:
  - name: Overview
    weight: 1
  - name: Materials
    weight: 2
tasks:
  - name: Overview
    weight: 1
  - name: Tasks
    weight: 2
  - name: Deliverables
    weight: 3
due:
  - name: Overview
    weight: 1
  - name: To Do List
    weight: 2
resources:
  - name: Overview
    weight: 1
  - name: Guides
    weight: 2
  - name: References
    weight: 3
