[build]
command = 'hugo --gc --minify'
publish = 'public'

[context.branch-deploy]
command = 'hugo --gc --minify -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL'

[context.production.environment]
HUGO_VERSION = '0.101.0'
HUGO_ENV = 'production'
